### Indexing (selecting data from tensors)
indexing with pytorch is similar to indexing with numpy 


In [2]:
#Create a tensor 

import torch 

x = torch.arange(1, 10).reshape(1,3,3)
x , x.shape 


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#lets index our first brarckt
x[0]
x[0][2]
x[0][2][2]
# you can use ":" to select "all" of a target dimension
x[:, 0]

# Index on x to return 9
print(x[0][2][2])

# index on x to return 3,6,9
print(x[:, 2])

tensor(9)

## Pytorch tensor and numpy


In [4]:
import torch 
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array , tensor  

array = array + 1
array , tensor 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
# NUmpy to tensor array 

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Trying to take randomm out of random 

In short how a neural network learns :

`start with random numbers -> tensor -> update random numbers to try and make them better representation of data -> againn -> again -> again...

To reduce the randomness in neural and Pytorch comes the concept of a **random seed** 

Essentially ehst the random seed does is a "flavour" the randomness

In [ ]:
import torch 

#Create two random tesnsor 
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.0382, 0.5764, 0.4075, 0.0968],
        [0.0877, 0.3534, 0.8207, 0.6840],
        [0.9614, 0.0541, 0.2213, 0.4939]])
tensor([[0.6799, 0.2323, 0.9981, 0.7256],
        [0.0170, 0.6721, 0.9693, 0.1217],
        [0.7605, 0.9896, 0.1786, 0.3923]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
# Lets make some random but reproducible tensors 

import torch

# set the problem seed 

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
