### Getting information from tensors 

1) Tensors are not right data type - To get data type from tensor use tensor.dtype
2) Tensors are not right shape - To know the shape of a tensor use tensor.shape
3) Tensors are not on right device - To get device from a tensor use tensor.device

In [1]:
import torch
#Creating a tensor 
some_tensor = torch.rand(3,4)
some_tensor

print(some_tensor)

#finding out some details 
print(some_tensor.dtype);
print(some_tensor.shape);
print(some_tensor.device);

tensor([[0.6973, 0.6447, 0.0967, 0.3427],
        [0.1628, 0.8778, 0.9257, 0.5915],
        [0.0673, 0.6334, 0.2841, 0.9338]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operations)

Tensors operation include 

* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix multiplication


In [2]:
# create a tensor 
tensor = torch.tensor([1, 2, 3])
tensor + 10

# multiply 
tensor * 10

#Subtract
tensor - 10

#try out Pytorch in-built functions 
torch.mul(tensor, 10)



tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of Multiplication in neural network in deep learning

1) Multiplication (Dot product)
2) Element wise Multiplication 

There are two rules that perform matrix multiplication needs to be satisfied 

1) The **inner dimension** must work
2) The resulting matrix has shape of the **outer dimension** 

In [3]:
#Elemnt wise multiplication 

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

#Matrix multiplication
torch.matmul(tensor, tensor)


value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor(14)


#### One of the most common errors in deep learning is shape 

In [5]:
import torch;

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])

torch.matmul(tensor_A , tensor_B);
 #torch.mm = torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

1 To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a
**transpose** operation. A transpose switches the axes or dimensions of a given tensor.


In [ ]:
import torch 
#transpose of a tensor 
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
print(f"Original shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above),tensor_B.T = {tensor_B.T}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions match")
print(f"Output shape : {torch.matmul(tensor_A, tensor_B.T).shape}")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above),tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions match
Output shape : torch.Size([3, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])
